# 2024-06-10 21:05
name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: thNylHx/Tools
        path: Tools-repo

    - name: Fork
      run: |
        curl https://raw.githubusercontent.com/thNylHx/Tools/main/Script/fork.sh | sh

###### Surge
      # 适配规则
    - name: Edit Ruleset/Block
      run: |
        cd Tools-repo/Ruleset/Block
        for file in *.list; do
          if [ "$file" != "Lan.list" ] ; then
            sed -i -e 's/, /,/g' \
                   -e 's/;/# /g' \
                   -e 's/host,/HOST,/g' \
                   -e 's/host-/HOST-/g' \
                   -e 's/-suffix/-SUFFIX/g' \
                   -e 's/-keyword/-KEYWORD/g' \
                   -e 's/ip-cidr/IP-CIDR/g' \
                   -e 's/-wildcard/-WILDCARD/g' \
                   -e 's/geoip/GEOIP/g' \
                   -e 's/HOST,/DOMAIN,/g' \
                   -e 's/HOST-/DOMAIN-/g' \
                   -e 's/IP6-CIDR,/IP-CIDR6,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e '/# 更新：/d' \
                   -e '/# AUTHOR:/d' \
                   -e '/# REPO:/d' \
                   -e '/# UPDATED:/d' \
                   -e '/# 数目: /d' \
                   -e '/# 规则: /d' \
                   -e '/404: Not Found/d' \
                   "$file"
            # 如果为IP规则且不包含no-resolve 则添加no-resolve
            awk '/^IP-/ && !/,no-resolve/ {print $0",no-resolve"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done

        # 转换 domain-set 为 rule-set
        for file in AdGuardChinese.list Ads_AWAvenue.list Ads_SukkaW.list; do
          if [ -f "$file" ]; then
            # 将以.开头的行的第一个.替换为 DOMAIN-SUFFIX,
            sed -i '/^\./s/^\./DOMAIN-SUFFIX,/' "$file"
            # 将除了以#开头、空行和以DOMAIN-SUFFIX开头之外的行，在行首添加 DOMAIN,
            sed -i '/^\s*$/b; /^\s*#/b; /^DOMAIN-SUFFIX,/b; s/^\([^#]\)/DOMAIN,\1/' "$file"
          else
            echo "$file not found."
          fi
        done

      # 追加规则
    - name: Copy custom rules
      run: |
        if [ -f "Tools-repo/Ruleset/Block/Reject.list" ] ; then
          cat Tools-repo/Ruleset/Block/Ads_RuCu6.list >> Tools-repo/Ruleset/Block/Reject.list
        else
          echo "$file not found."
        fi

      # 去重排序
    - name: Remove duplicates and lines 
      run: |
        cd Tools-repo/Ruleset/Block
        shopt -s nullglob  # 避免没有匹配的文件时保留原始通配符
        for file in Reject.list; do
          if [ -f "$file" ]; then
            sorted_file="sorted_${file}"
            # 使用 grep 去掉包含 # 的行
            grep -v '^\s*#' "$file" | grep -v '^\s*$' | sort | uniq > "$sorted_file"
            mv "$sorted_file" "$file"
          else
            echo "$file not found."
          fi
        done
      shell: bash

###### Commit
    - name: Add and Commits
      run: |
        cd Tools-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
