# 2024-06-28 12:00
name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: thNylHx/Tools
        path: Tools-repo

    - name: Fork
      run: |
        curl https://raw.githubusercontent.com/thNylHx/Tools/main/Script/fork.sh | sh

###### Surge ######
      # 适配规则
    - name: Edit Transfer
      run: |
        cd Tools-repo/Transfer
        for file in BlockAds.list; do
          if [ "$file" != "Lan.list" ] ; then
            sed -i -e 's/, /,/g' \
                   -e 's/;/# /g' \
                   -e 's/host,/HOST,/g' \
                   -e 's/host-/HOST-/g' \
                   -e 's/-suffix/-SUFFIX/g' \
                   -e 's/-keyword/-KEYWORD/g' \
                   -e 's/ip-cidr/IP-CIDR/g' \
                   -e 's/-wildcard/-WILDCARD/g' \
                   -e 's/geoip/GEOIP/g' \
                   -e 's/HOST,/DOMAIN,/g' \
                   -e 's/HOST-/DOMAIN-/g' \
                   -e 's/IP6-CIDR,/IP-CIDR6,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e '/# 更新：/d' \
                   -e '/# AUTHOR:/d' \
                   -e '/# REPO:/d' \
                   -e '/# UPDATED:/d' \
                   -e '/# 数目: /d' \
                   -e '/# 规则: /d' \
                   -e '/404: Not Found/d' \
                   "$file"
            # 如果为IP规则且不包含no-resolve 则添加no-resolve
            awk '/^IP-/ && !/,no-resolve/ {print $0",no-resolve"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done

      # 追加规则
    - name: Copy custom rules
      run: |
        # 获取当前时间
        current_date=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')

        # 把 BlockAd 同步到 BlockAdG 存在
        if [ -f "Tools-repo/Ruleset/Block/BlockAdG.list" ] ; then
          echo "#!name = Twitter" >> Tools-repo/Ruleset/Block/BlockAdG.list
          echo "#!desc = 分流规则" >> Tools-repo/Ruleset/Block/BlockAdG.list
          echo "#!date = $current_date" >> Tools-repo/Ruleset/Block/BlockAdG.list
          echo "#!author = " >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockAd.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockAdb.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockAdg.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockAds.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockEasyListChina.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockAdvertising.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockHijacking.list >> Tools-repo/Ruleset/Block/BlockAdG.list
          cat Tools-repo/Transfer/BlockTracking.list >> Tools-repo/Ruleset/Block/BlockAdG.list
        else
          echo "$file not found."
        fi

        # 把 TwitterIP 同步到 Twitter
        if [ -f "Tools-repo/Ruleset/Media/Twitter.list" ] ; then
         echo "#!name = Twitter" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "#!desc = 分流规则" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "#!date = $current_date" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "#!author = " >> Tools-repo/Ruleset/Media/Twitter.list
         echo "" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "" >> Tools-repo/Ruleset/Media/Twitter.list
         cat Tools-repo/Transfer/Twitter.list >> Tools-repo/Ruleset/Media/Twitter.list
         echo "" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "" >> Tools-repo/Ruleset/Media/Twitter.list
         echo "#!name = TwitterIP" >> Tools-repo/Ruleset/Media/Twitter.list
         cat Tools-repo/Transfer/TwitterIP.list >> Tools-repo/Ruleset/Media/Twitter.list
        else
          echo "$file not found."
        fi

      # 去重排序
    - name: Remove duplicates and lines 
      run: |
        cd Tools-repo/Ruleset/Block
        shopt -s nullglob  # 避免没有匹配的文件时保留原始通配符
        for file in BlockAdG.list; do
          if [ -f "$file" ]; then
            sorted_file="sorted_${file}"
            # 使用 grep 去掉包含 # 的行
            grep -v '^\s*#' "$file" | grep -v '^\s*$' | sort | uniq > "$sorted_file"
            mv "$sorted_file" "$file"
          else
            echo "$file not found."
          fi
        done
      shell: bash

###### Commit
    - name: Add and Commit
      run: |
        cd Tools-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 5
