# 2024-06-10 21:05
name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: thNylHx/Tools
        path: Tools-repo

    - name: 复刻
      run: |
        curl https://raw.githubusercontent.com/thNylHx/Tools/main/Script/fork.sh | sh

###### Surge
      # 适配规则
    - name: Edit Ruleset
      run: |
        for dir in Tools-repo/Ruleset Tools-repo/Ruleset/Block Tools-repo/Ruleset/Media Tools-repo/Ruleset/Other; do
        if [ -d "$dir" ]; then
        cd "$dir"
        for file in BlockAds.list; do
          if [ "$file" != "Lan.list" ] ; then
            sed -i -e 's/, /,/g' \
                   -e 's/;/# /g' \
                   -e 's/host,/HOST,/g' \
                   -e 's/host-/HOST-/g' \
                   -e 's/-suffix/-SUFFIX/g' \
                   -e 's/-keyword/-KEYWORD/g' \
                   -e 's/ip-cidr/IP-CIDR/g' \
                   -e 's/-wildcard/-WILDCARD/g' \
                   -e 's/geoip/GEOIP/g' \
                   -e 's/HOST,/DOMAIN,/g' \
                   -e 's/HOST-/DOMAIN-/g' \
                   -e 's/IP6-CIDR,/IP-CIDR6,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e '/# 更新：/d' \
                   -e '/# AUTHOR:/d' \
                   -e '/# REPO:/d' \
                   -e '/# UPDATED:/d' \
                   -e '/# 数目: /d' \
                   -e '/# 规则: /d' \
                   -e '/404: Not Found/d' \
                   "$file"
                   
            # 如果为IP规则且不包含no-resolve 则添加no-resolve
            awk '/^IP-/ && !/,no-resolve/ {print $0",no-resolve"; next} {print}' "$file" > tmpfile
            mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done

        # 格式转换 domain-set 为 rule-set
        for file in ChinaIP.list; do
          if [ -f "$file" ]; then
          
            # 转换 domain-set 为 rule-set
            # # 将以.开头的行的第一个.替换为 DOMAIN-SUFFIX,
            # sed -i '/^\./s/^\./DOMAIN-SUFFIX,/' "$file"
            # # 将除了以#开头、空行和以DOMAIN-SUFFIX开头之外的行，在行首添加 DOMAIN,
            # sed -i '/^\s*$/b; /^\s*#/b; /^DOMAIN-SUFFIX,/b; s/^\([^#]\)/DOMAIN,\1/' "$file"
            
            # 识别并转换 IPv4 和 IPv6 CIDR，并在末尾添加 no-resolve
            sed -i -E 's|^(([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+)$|IP-CIDR,\1,no-resolve|' "$file"
            sed -i -E 's|^([0-9a-fA-F:]+/[0-9]+)$|IP-CIDR6,\1,no-resolve|' "$file"
          else
            echo "$file not found."
          fi
        done

        cd - > /dev/null  # 返回到上一级目录，并抑制输出
          else
            echo "Directory $dir not found."
         fi
        done

      # 追加规则
    - name: Copy custom rules
      run: |
      
        # if [ -f "Tools-repo/Ruleset/Ads.list" ] ; then
        #   cat Tools-repo/Ruleset/Block/BlockAds.list >> Tools-repo/Ruleset/Ads.list
        # else
        #   echo "$file not found."
        # fi

        # 合并 YouTubeMusic 到 YouTube
        if [ -f "Tools-repo/Ruleset/Media/YouTube.list" ] ; then
         echo "" >> Tools-repo/Ruleset/Media/YouTube.list
         echo "" >> Tools-repo/Ruleset/Media/YouTube.list
         cat Tools-repo/Ruleset/Media/YouTubeMusic.list >> Tools-repo/Ruleset/Media/YouTube.list
         rm -rf Tools-repo/Ruleset/Media/YouTubeMusic.list
        else
         echo "$file not found."
        fi
        
        # 合并 NetflixIP 到 Netflix
        if [ -f "Tools-repo/Ruleset/Media/Netflix.list" ] ; then
         echo "" >> Tools-repo/Ruleset/Media/Netflix.list
         echo "" >> Tools-repo/Ruleset/Media/Netflix.list
         cat Tools-repo/Ruleset/Media/NetflixIP.list >> Tools-repo/Ruleset/Media/Netflix.list
         rm -rf Tools-repo/Ruleset/Media/NetflixIP.list
        else
         echo "$file not found."
        fi
        
        # 合并 Instagram 到 Facebook
        if [ -f "Tools-repo/Ruleset/Other/Facebook.list" ] ; then
         echo "" >> Tools-repo/Ruleset/Other/Facebook.list
         echo "" >> Tools-repo/Ruleset/Other/Facebook.list
         cat Tools-repo/Ruleset/Other/Instagram.list >> Tools-repo/Ruleset/Other/Facebook.list
         rm -rf Tools-repo/Ruleset/Other/Instagram.list
        else
         echo "$file not found."
        fi
        
        # 合并 GoogleCN & GoogleCNProxyIP & GoogleEarth & GoogleFCM 到 Google
        if [ -f "Tools-repo/Ruleset/Other/Google.list" ] ; then
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         cat Tools-repo/Ruleset/Other/GoogleCN.list >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         cat Tools-repo/Ruleset/Other/GoogleCNProxyIP.list >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         cat Tools-repo/Ruleset/Other/GoogleEarth.list >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         echo "" >> Tools-repo/Ruleset/Other/Google.list
         cat Tools-repo/Ruleset/Other/GoogleFCM.list >> Tools-repo/Ruleset/Other/Google.list
         rm -rf Tools-repo/Ruleset/Other/GoogleCN.list
         rm -rf Tools-repo/Ruleset/Other/GoogleCNProxyIP.list
         rm -rf Tools-repo/Ruleset/Other/GoogleEarth.list
         rm -rf Tools-repo/Ruleset/Other/GoogleFCM.list
        else
         echo "$file not found."
        fi

      # 去重排序
    - name: Remove duplicates and lines 
      run: |
        cd Tools-repo/Ruleset/Media
        shopt -s nullglob  # 避免没有匹配的文件时保留原始通配符
        for file in Y.list; do
          if [ -f "$file" ]; then
            sorted_file="sorted_${file}"
            # 使用 grep 去掉包含 # 的行
            grep -v '^\s*#' "$file" | grep -v '^\s*$' | sort | uniq > "$sorted_file"
            mv "$sorted_file" "$file"
          else
            echo "$file not found."
          fi
        done
      shell: bash

###### Commit
    - name: Add and Commits
      run: |
        cd Tools-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
