# 2024-06-10 21:05
name: Fork1 & Edit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0/12 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: thNylHx/Tools
        path: Tools-repo

    - name: 复刻
      run: |
        curl https://raw.githubusercontent.com/thNylHx/Tools/main/Script/fork1.sh | sh

###### Surge
      # 适配规则
    - name: Edit Ruleset
      run: |
        cd Tools-repo/Ruleset/Other

        # 格式转换 domain-set 为 rule-set
        for file in GoogleIP.list TwitterIP.list; do
          if [ -f "$file" ]; then
            
            # 识别并转换 IPv4 和 IPv6 CIDR, 并在末尾添加 no-resolve
            sed -i -E 's|^(([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]+)$|IP-CIDR,\1,no-resolve|' "$file"
            sed -i -E 's|^([0-9a-fA-F:]+/[0-9]+)$|IP-CIDR6,\1,no-resolve|' "$file"
          else
            echo "$file not found."
          fi
        done

###### Commit
    - name: Add and Commits
      run: |
        cd Tools-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
